spring.application.name=event-management-system

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-floral-tree-b3bwxhn2-pooler.c-4.ap-southeast-1.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_Bkb7UMzeZA9C}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}
spring.jackson.deserialization.fail-on-null-for-primitives=false